### ISSUE TITLE
Gravierender Fehler entdeckt

### ISSUE THREAD

**Issue by harrydehix** [MrTK-Dev/Iter-Salis-Forsaken-Expert#4]
**Modpack version**
Jede

**Can the issue be reproduced?**
Ja (er ist immer vorhanden)

**Link(s) for Crashes/Suggestions**
https://www.youtube.com/watch?v=rv3u2GbLl_4

**Detailed Description of your Issue**
Ich denke, dass Timo ein großer Bug ist und entfernt werden sollte 💩💩💩💩💩💩💩💩💩💩

**Comment by MrTK-Dev** [comment]
Bug fixed in #0.0.2
